import React from "react";
import "../../DashboardHome.css";

export default function DashboardHome() {
  return (
    <div className="dashboard-home">
      <header className="dashboard-header">
        <div>
          <h1>Welcome back, Admin 👋</h1>
          <p className="welcome-text">
            Here’s a quick overview of your platform today.
          </p>
        </div>
      </header>

      {/* Summary Cards */}
      <section className="dashboard-summary">
        <div className="summary-card">
          <h3>Total Customers</h3>
          <p>248</p>
          <span className="trend positive">▲ 12% from last month</span>
        </div>

        <div className="summary-card">
          <h3>Active Projects</h3>
          <p>36</p>
          <span className="trend neutral">No change</span>
        </div>

        <div className="summary-card">
          <h3>Pending Reports</h3>
          <p>5</p>
          <span className="trend negative">▼ 3 since last week</span>
        </div>

        <div className="summary-card">
          <h3>System Health</h3>
          <p>99.8%</p>
          <span className="trend positive">All systems operational</span>
        </div>
      </section>

      {/* Recent Activity */}
      <section className="recent-activity">
        <h2>Recent Activity</h2>
        <ul className="activity-list">
          <li>
            🟢 <span>New customer “Acme Corp” registered</span>
          </li>
          <li>
            🟠 <span>Project “Fiber Rollout 2025” updated</span>
          </li>
          <li>
            🔵 <span>New report generated by user John Doe</span>
          </li>
          <li>
            🟢 <span>License verification completed successfully</span>
          </li>
        </ul>
      </section>
    </div>
  );
}
